---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart cloudflared
  ansible.builtin.systemd:
    name: cloudflared
    state: restarted
    daemon_reload: true
