#!/usr/bin/env bash
# Interactive wizard: writes ansible/group_vars/local.yml
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT_DIR}/ansible/group_vars/local.yml"

prompt() {
  local var="$1"
  local text="$2"
  local default="${3:-}"
  local reply
  if [[ -n "$default" ]]; then
    read -r -p "${text} [${default}]: " reply
    reply="${reply:-$default}"
  else
    read -r -p "${text}: " reply
  fi
  printf -v "$var" '%s' "$reply"
}

yn() {
  local text="$1"
  local default="${2:-n}"
  local reply
  read -r -p "${text} [y/N]: " reply
  reply="${reply:-$default}"
  [[ "$reply" =~ ^[Yy] ]]
}

echo "=== Moltbot homelab — configuration wizard ==="
echo "Output: ${OUT}"
echo

prompt PRESET "Preset (minimal | voice | storage | photos | full)" "minimal"
prompt TZ_VAL "Timezone" "Europe/Moscow"
prompt CITY "Default weather city (empty = ask each time)" ""
prompt DISTRICT "Default weather district" ""

ENABLE_VOICE=false
ENABLE_OLLAMA=true
ENABLE_WHISPER_SVC=false
ENABLE_TIMER=false
ENABLE_BACKUP=false
WEB_SEARCH="off"

case "${PRESET}" in
  voice)
    ENABLE_VOICE=true
    ENABLE_WHISPER_SVC=false
    ENABLE_HERMES_NPU=false
    WEB_SEARCH="searxng"
    ;;
  full)
    ENABLE_VOICE=true
    ENABLE_WHISPER_SVC=false
    ENABLE_HERMES_NPU=false
    ENABLE_TIMER=true
    ENABLE_BACKUP=true
    WEB_SEARCH="searxng"
    ;;
esac

VOICE_BACKEND="hermes"
ENABLE_HERMES_NPU="${ENABLE_HERMES_NPU:-false}"

if yn "Install voice stack (Hermes wake/STT/TTS)?" "$([ "$ENABLE_VOICE" = true ] && echo y || echo n)"; then
  ENABLE_VOICE=true
fi
if yn "Use legacy whisper.cpp voice MVP instead of Hermes?" "n"; then
  VOICE_BACKEND="legacy"
  if yn "Enable whisper-server systemd (legacy)?" "$([ "$ENABLE_WHISPER_SVC" = true ] && echo y || echo n)"; then
    ENABLE_WHISPER_SVC=true
  fi
else
  if yn "Enable FastFlowLM NPU STT (flm-asr)?" "$([ "$ENABLE_HERMES_NPU" = true ] && echo y || echo n)"; then
    ENABLE_HERMES_NPU=true
  fi
fi
if yn "Install Ollama and pull models?" "y"; then
  ENABLE_OLLAMA=true
else
  ENABLE_OLLAMA=false
fi
if yn "Enable daily backup timer?" "$([ "$ENABLE_BACKUP" = true ] && echo y || echo n)"; then
  ENABLE_BACKUP=true
fi

prompt WHISPER_MODEL "Whisper model (small | medium | large-v3)" "medium"
prompt TTS "TTS engine (piper | silero)" "piper"
prompt BACKUP_DIR "Backup directory" "/backup/homelab"

HA_URL=""
HA_TOKEN=""
if yn "Configure Home Assistant integration now?"; then
  prompt HA_URL "HOME_ASSISTANT_URL (e.g. http://localhost:8123)" "http://localhost:8123"
  prompt HA_TOKEN "HOME_ASSISTANT_TOKEN (long-lived)" ""
fi

NC_PASS=""
if [[ "${PRESET}" == "full" || "${PRESET}" == "storage" ]]; then
  if yn "Set Nextcloud admin password?"; then
    read -r -s -p "NEXTCLOUD_ADMIN_PASSWORD: " NC_PASS
    echo
  fi
fi

mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
---
# Generated by scripts/configure-wizard.sh on $(date -Iseconds)

moltbot_preset: ${PRESET}

moltbot_enable_voice: ${ENABLE_VOICE}
voice_backend: ${VOICE_BACKEND}
hermes_enable_npu_stt: ${ENABLE_HERMES_NPU}
moltbot_enable_systemd_flm_asr: ${ENABLE_HERMES_NPU}
moltbot_enable_ollama: ${ENABLE_OLLAMA}
moltbot_enable_systemd_whisper: ${ENABLE_WHISPER_SVC}
moltbot_enable_systemd_timer_worker: ${ENABLE_TIMER}
moltbot_enable_backup_timer: ${ENABLE_BACKUP}

tz: ${TZ_VAL}
default_weather_city: "${CITY}"
default_weather_district: "${DISTRICT}"

web_search_provider: ${WEB_SEARCH}
searxng_base_url: http://searxng:8080
searxng_public_url: http://localhost:18081

home_assistant_url: "${HA_URL}"
home_assistant_token: "${HA_TOKEN}"

nextcloud_admin_password: "${NC_PASS}"

whisper_model_name: ${WHISPER_MODEL}
tts_engine: ${TTS}
voice_user: "{{ ansible_env.USER }}"

backup_dir: ${BACKUP_DIR}
backup_retention_days: 14
EOF

chmod 600 "${OUT}"
echo
echo "Saved ${OUT}"
echo "Next: make install   (or make install-${PRESET})"
